# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-JFileDialog
version:      1.4
version_from: lib/Tk/JFileDialog.pm
installdirs:  site
requires:
    Tk:                            0
    Tk::JBrowseEntry:              4.63

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
